### ISSUE TITLE
To Dos

### ISSUE THREAD

**Issue by jdlehman** [jdlehman/bumblebee_flight#1]
## TODO
- [x] Update barrier graphics
- [x] Update menu graphics (especially start button)
- [x] Fixed bee, moving barriers (smaller world without camera)
- [x] Decide on gameplay and difficulty
- [x] Fix jumpy mountain parallax (mountain in background just twitches)
- [ ] Figure out a better way to persist data and remove the need for globals. (ex: game.state.states['stateName'].data)
- [ ] Figure out if parameters can be passed into state objects (other than game)
- [ ] Add sound on/off toggle on menu screen
- [x] Loop song
- [x] Replace obstacles with real obstacles
- [x] Passages must be generated within a certain range of the previous one. It must be physically possible to get to the next one with teh bee.  (Ex passage cannot be on the bottom the nthe top of the screen as this is not even close to possible). EIther this or adjust bee movement to compensate. Player must at least think that they can get through the next obstacle
- [x] Don't let the bee leave the top or bottom of the world
- [x] Add scoring
- [x] Add start game
- [x] Add restart game
- [x] End the game on a collision with an obstacle

**Comment by paulog** [comment]
Better place for this.  Ty!
